apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: probe-write
  namespace: default
  labels:
    app: probe-write
spec:
  selector:
    matchLabels:
      app: probe-write
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: probe-write
      labels:
        app: probe-write
    spec:
      hostNetwork: true
      hostPID: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: probe-write
        imagePullPolicy: Always
        image: quay.io/julienbalestra/debug-app:latest
        command:
        - /usr/local/bin/probe-write
        - -sleep
        - "600"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/probe-write
            - -health
          initialDelaySeconds: 5
          periodSeconds: 60
          failureThreshold: 10
          timeoutSeconds: 601
