apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: probe-failures
  namespace: default
  labels:
    app: probe-failures
spec:
  selector:
    matchLabels:
      app: probe-failures
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: probe-failures
      labels:
        app: probe-failures
    spec:
      hostNetwork: true
      hostPID: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: probe-failures
        imagePullPolicy: Always
        image: quay.io/julienbalestra/debug-app:latest
        command:
        - /usr/local/bin/probe-failures
        volumeMounts:
        - name: probe-failures
          mountPath: /var/lib/probe-failures/
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/probe-failures
            - -health
          initialDelaySeconds: 1
          periodSeconds: 11
          failureThreshold: 10
          timeoutSeconds: 5

      volumes:
      - emptyDir:
        name: probe-failures
